### ISSUE TITLE
YOUTUBE_TV_CLIENT_ID

### ISSUE THREAD

**Issue by 89z** [bromix/vue3-sourcemaps-not-working#1]
Good afternoon. I know this is the wrong repo, but I am trying to figure out where you found these values:

~~~py
YOUTUBE_TV_CLIENT_ID = '861556708454-d6dlm3lh05idd8npek18k6be8ba3oc68.apps.googleusercontent.com'
YOUTUBE_TV_CLIENT_SECRET = 'SboVhoG9s0rNafixCSGGKXAT'
~~~

It looks like you deleted your own repository, but I think I found the oldest commit here:

https://github.com/roondar/plugin.video.bromix.youtube/commit/851b37d9

where you added this code, but I didnt see any comment as to how you came about this information. it seems many people have just copied the secret in the years since, but I havent seen a single person explain where the client info actually came from. If you have any information, it would be appreciated.

**Comment by 89z** [comment]
I figured it out - you have to go to youtube.com/tv - then click "Sign in with a web browser"

**Comment by bromix** [comment]
That is correct 😄
